# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Mao
email: mizzao@gmail.com
description: > # this means to ignore newlines until "baseurl:"

url: 'http://www.andrewmao.net' # the base hostname & protocol for your site
baseurl: '' # the subpath of your site, e.g. /blog
permalink: pretty

google_analytics: UA-106157291-1

# Build settings
markdown: kramdown

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: mizzao@gmail.com
  facebook:
  flickr:
  github: mizzao
  instagram: # chairman.maos.chicken
  linkedin: mizzao
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: mizzao
  # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  stackoverflow: users/586086/andrew-mao
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
